version: "3.4"

services:
  mongo:
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: tungnk
      MONGO_INITDB_ROOT_PASSWORD: 160199

  mongo-express: # this service is a MongoDB UI, and is optional
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rasa
      ME_CONFIG_MONGODB_ADMINPASSWORD: example