# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: vi

pipeline:
  - name: "WhitespaceTokenizer"
  - name: "CountVectorsFeaturizer"
  - name: "DIETClassifier"
    entity_recognition: False
    epochs: 20
  - name: ResponseSelector
    epochs: 20

policies:
  - name: TEDPolicy
    max_history: 5
    epochs: 20
  - name: MemoizationPolicy
  - name: RulePolicy
